# fly.toml file generated for game-master-companion on 2023-03-22T17:21:19+01:00

app = "potato-tracker"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "cdg"
processes = []

[env]

[experimental]
  auto_rollback = true

[mounts]
    source="potato"
    destination="app/potato"